package main.model;
// Generated 15-dic-2016 13:44:58 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "hospital", catalog = "larioja")
public class Hospital implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "medico", nullable = false, length = 100)
    private String medico;

    @Column(name = "numeroconsulta", nullable = false)
    private int numeroconsulta;

    @Temporal(TemporalType.TIME)
    @Column(name = "horainicio", nullable = false, length = 8)
    private Date horainicio;

    @Temporal(TemporalType.TIME)
    @Column(name = "horafin", nullable = false, length = 8)
    private Date horafin;

    public Hospital() {
    }

    public Hospital(String medico, int numeroconsulta, Date horainicio, Date horafin) {
        this.medico = medico;
        this.numeroconsulta = numeroconsulta;
        this.horainicio = horainicio;
        this.horafin = horafin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMedico() {
        return this.medico;
    }

    public void setMedico(String medico) {
        this.medico = medico;
    }

    public int getNumeroconsulta() {
        return this.numeroconsulta;
    }

    public void setNumeroconsulta(int numeroconsulta) {
        this.numeroconsulta = numeroconsulta;
    }

    public Date getHorainicio() {
        return this.horainicio;
    }

    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }

    public Date getHorafin() {
        return this.horafin;
    }

    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }

}
